apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: annobib-production

resources:
  - ../../base
  - namespace.yaml

images:
  - name: annobib-app
    newName: us-central1-docker.pkg.dev/annobib-prod/annobib/annobib-app
    newTag: latest

replicas:
  - name: annobib-app
    count: 3

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml
  - path: sa-patch.yaml
