apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: annobib-secrets
  labels:
    app: annobib
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: annobib-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: NUXT_AUTH0_DOMAIN
      remoteRef:
        key: NUXT_AUTH0_DOMAIN
    - secretKey: NUXT_AUTH0_CLIENT_ID
      remoteRef:
        key: NUXT_AUTH0_CLIENT_ID
    - secretKey: NUXT_AUTH0_CLIENT_SECRET
      remoteRef:
        key: NUXT_AUTH0_CLIENT_SECRET
    - secretKey: NUXT_STRIPE_SECRET_KEY
      remoteRef:
        key: NUXT_STRIPE_SECRET_KEY
    - secretKey: NUXT_STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: NUXT_STRIPE_WEBHOOK_SECRET
    - secretKey: NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    - secretKey: NUXT_OPENAI_API_KEY
      remoteRef:
        key: NUXT_OPENAI_API_KEY
    - secretKey: NUXT_SESSION_PASSWORD
      remoteRef:
        key: NUXT_SESSION_PASSWORD
    - secretKey: NUXT_GOOGLE_BOOKS_API_KEY
      remoteRef:
        key: NUXT_GOOGLE_BOOKS_API_KEY
