apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bibanna-production

resources:
  - ../../base
  - namespace.yaml

images:
  - name: bibanna-app
    newName: gcr.io/bibanna-prod/bibanna-app
    newTag: latest

replicas:
  - name: bibanna-app
    count: 3

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml
