apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: bibanna-base

namespace: bibanna

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: bibanna
  app.kubernetes.io/managed-by: kustomize
