apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: annobib-base

namespace: annobib

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml
  - migration-job.yaml
  - networkpolicy.yaml
  - external-secret.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: annobib
  app.kubernetes.io/managed-by: kustomize
