apiVersion: v1
kind: Service
metadata:
  name: bibanna-app
  labels:
    app: bibanna
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: bibanna
    component: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bibanna-app
  labels:
    app: bibanna
